[package]
name = "whistle_compiler"
version = "0.1.0"
authors = ["the Whistle authors"]
edition = "2018"

[dependencies]
whistle_common = { path = "../common/" }
whistle_ast = { path = "../ast/" }
wasm-encoder = "0.4.0"
